run.go
Issue https://github.com/Scalingo/cli/issues/233
=> Handle the size flag

deployments.go
=> Add support of deployment of an archive

apps.go, scalingomock/gomock_api.go, scalingomock/gomock_appsservice.go
=> Add App#Rename method

apps.go, scalingomock/gomock_api.go, scalingomock/gomock_appsservice.go
=> Fix interface method signature for AppsRename and AppsTransfer

addons_providers.go
=> be less strict about addon name

events_boilerplate.go, events_types.go, events_types_test.go
=> Add edit_app event handling

domains.go
=> Add domains#show

auth_api_token.go, client.go, tokens.go
=> Auth endpoint and authenticated client

metrics.go
=> Add metrics constants

CHANGELOG.md, keys.go
Related to https://github.com/Scalingo/authentication-service/issues/118
=> Use the auth service for the keys endpoints

CHANGELOG.md, github_link.go
=> Add Github Link

events_boilerplate.go, events_types.go
=> Add support for alert and autoscaler events

notifier_types.go, notifiers.go
=> Implement the configuration of the email notifier

users.go
=> FirstName and LastName merged into Name for User

addons.go, alerts.go, apps.go, autoscalers.go, collaborators.go, container.go, domains.go, events_types.go, notification_platforms.go, notifier_types.go, operations.go
=> Add app_id to models which have been modified in the API, ans switch from denormalized to ids array

domains.go, domains_test.go, subresources.go
=> Add DomainSetCanonical and DomainUnsetCanonical methods

addons.go
Related to https://github.com/Scalingo/cli/issues/398
=> Add addon logs

client.go, http/client.go
=> Fix regression, get back Endpoint and AuthEndpoint in ClientConfig, add DatabaseAPIEndpoint and configure according HTTP clients

alerts.go
Related to Scalingo/scalingo-alerter-service#93
=> Add support for DurationBeforeTrigger

domains.go
=> Add ACME related fields

addons_providers.go
Fix #88
This field is actually never used, whatever the plan.
=> Remove ShortDescription

notification_platforms.go
=> Add missing fields to NotificationPlatform struct

notifier_types.go, notifiers.go
=> Add attribute 'send_all_alerts' to Notifier

notifier_types.go, notifiers.go
=> Correctly handle SelectedEventIDs for Notifier

http/api_request.go
=> Display request ID

apps.go
=> Add app settings to the App struct

regions.go
Related to Scalingo/authentication-service#261
=> Add a Default attribute to a region

apps.go
=> Add missing possible param when creating a Scalingo app

http/api_request.go, http/client.go, http/errors.go, tokens.go
=> errgo.Mask is terrible

apps.go, client.go, migrations.go, region_migrations.go
Related to Scalingo/storky/issues/1
=> Add region migrations service

CHANGELOG.md, backups.go
=> Add BackupCreate method

review_apps.go, scm_repo_link.go
=> Add repo link calls

backups.go
To be merged along with https://github.com/Scalingo/database-api-service/issues/163 
Related to Scalingo/cli#452
=> Backup creation returns a backup

databases.go
=> Add periodic backups configuration method

CHANGELOG.md, databases.go
=> Add DatabaseShow method

CHANGELOG.md, databases.go
Related to Scalingo/database-api-service#165
=> sand_ip is now private_ip

databases.go
Related to Scalingo/appsdeck-database#1181
=> PeriodicBackupsScheduledAt is a slice of int

stacks.go
Related to https://github.com/Scalingo/api/issues/1515
=> Add stack aliases

CHANGELOG.md, alerts_test.go, apps_test.go, client.go, client_test.go, domains_test.go, events_test.go, examples/app_show/main.go, examples/backup_download/main.go, http/client.go, regions.go
=> Add region support

scm_repo_link.go
=> Fix HTTP method of SCMRepoLinkUpdate

CHANGELOG.md, events_boilerplate.go, events_structs.go, events_user.go
=> Add support for the new SCM events

CHANGELOG.md, events_boilerplate.go, events_structs.go, events_user.go, scm_integrations.go
Related to Scalingo/authentication-service#299
=> Add event NewIntegration

CHANGELOG.md, events_boilerplate.go, events_structs.go
=> Add support for new_user event

CHANGELOG.md, scm_repo_link.go
=> Remove incorrect fields in SCMRepoLinkParams for PATCH update

CHANGELOG.md, scm_repo_link.go
=> SCMType is also returned by the API

CHANGELOG.md, http/errors.go
=> Better handling of 404 from API

CHANGELOG.md, README.md, client.go, http/api_request.go, http/client.go, version.go
=> Display user agent in debug output

region_migrations.go
Related to https://github.com/Scalingo/storky/pull/7
=> Add storky run endpoint

events_structs.go
=> Add event struct and type for Addon Update Status

events_structs.go
Related to https://github.com/Scalingo/api/pull/1620
=> Correctly set fields for event AddonUpdated

addons.go
=> Use a propose AddonProvisionParams struct instead of using a sub-part of an Addon

CHANGELOG.md, region_migrations.go
Related to https://github.com/Scalingo/one-stop-shop/issues/87
=> [Migrations] Add aborting status

CHANGELOG.md, README.md, events_boilerplate.go
Related to https://github.com/Scalingo/cli/issues/556
=> [event] Fix support for addon_updated and start_region_migration

CHANGELOG.md, deployments.go
Linked to https://github.com/Scalingo/cli/issues/562
=> Add HasFailed and HasFailedString methods to deployments helpers

README.md
link to http/errors and dev documentation for the details
=> Add to readme HTTP errors references

CHANGELOG.md, log_drains.go, log_drains_test.go
Related to https://github.com/Scalingo/cli/issues/554
=> Log drains: delete command

CHANGELOG.md, events_structs.go
Fix https://github.com/Scalingo/cli/issues/569
=> Fix an infinite reccursion on some events

CHANGELOG.md, log_drains.go, log_drains_test.go
Related https://github.com/Scalingo/cli/issues/571
=> list log_drains by DB

CHANGELOG.md, log_drains.go, log_drains_test.go
Related to #Scalingo/cli/issues/571
=> add log drain to an addon

CHANGELOG.md, log_drains.go, log_drains_test.go
Remove a log drain from a DB (with addon uuid)
Related to Scalingo/cli/issues/576
=> Remove log drain from an addon

deployments.go
Close #176 
Need to be merged before the [CLI issue](https://github.com/Scalingo/cli/issues/585) and make a new release.
=> Add `queued` deployment status

CHANGELOG.md, users.go
I decided to keep the retro-compatibility to prevent the dump of a new major version.
=> Add UserStopFreeTrial method

http/api_request.go, http/client.go, http/httpmock/client_mock.go, mocks_sig.json
=> Add support for unauthenticated clients

http/errors.go
and fix the link as the page moved
=> Doc link should use https

CHANGELOG.md, apps.go
=> Add Flags field to App

CHANGELOG.md, deployments.go
Related to https://github.com/Scalingo/git-repository-core/pull/59/
=> Add named constants to deployment stream event

CHANGELOG.md, events_boilerplate.go, events_structs.go
=> feat(event): add suport for notifier events

CHANGELOG.md, client.go
=> feat(http): add user agent to auth and DB API requests

CHANGELOG.md, domains.go
Relate https://github.com/Scalingo/api/pull/1841
=> feat: add SSL status in domain

databases.go
creating and updating status are new
=> feat(database): add two new statuses

CHANGELOG.md, cron_tasks.go, cron_tasks_test.go, mocks_sig.json, scalingomock/api_mock.go, scalingomock/crontasksservice_mock.go
Related to [CRON-25]
[CRON-25]: https://scalingo.atlassian.net/browse/CRON-25
=> Removed POST and create GET methods for cron tasks

CHANGELOG.md, events_structs.go
Related to [CRON-60]
[CRON-60]: https://scalingo.atlassian.net/browse/CRON-60
=> Add Deployment uuid to Deployemtn Event / fix typo

.github/pull_request_template.md
=> chore(github): add a pull request template

CHANGELOG.md, apps.go
=> Fix a typo update_at -> updated_at

CHANGELOG.md, addons.go
=> Add ProvisionedAt and DeprovisionedAt fields on the addon

.github/dependabot.yml
=> feat(dependabot): Monthly + EtienneM assigned to review as owner of the project

CHANGELOG.md, apps.go, apps_test.go
Related to https://github.com/Scalingo/cli/issues/605
=> feat(apps): add AppsRouterLogs function

CHANGELOG.md, scm_repo_link.go
See API doc: https://developers.scalingo.com/scm_repo_link#get-all-scm-integration-links-linked-by-your-account
=> Add SCMRepoLinkList method

CHANGELOG.md, domains.go, domains_test.go, mocks_sig.json, scalingomock/api_mock.go, scalingomock/domainsservice_mock.go
=> feat(domains): add DomainSetCertificate and DomainUnsetCertificate methods

CHANGELOG.md, events_boilerplate.go, events_structs.go
[UFSSP-56]
[UFSSP-22]
[UFSSP-56]: https://scalingo.atlassian.net/browse/UFSSP-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UFSSP-22]: https://scalingo.atlassian.net/browse/UFSSP-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: hds_contact_update and create_data_access_consent events

CHANGELOG.md, events_boilerplate.go, events_structs.go, events_token.go
[DOC-89]
[DOC-89]: https://scalingo.atlassian.net/browse/DOC-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(events): add token events

CHANGELOG.md, events_addon.go, events_structs.go
=> refactor(events): addon events in separate file

CHANGELOG.md, addons_providers.go
The Structure Plan and Addon Provider has changed.
Pricing and Category structures have been had.
Fix #268
=> fix(addon provider): add missing fields for addon providers endpoint

CHANGELOG.md, addons_providers.go
Deleted structure and fields related to pricing
=> fix(addons providers): delete all fields related to price

CHANGELOG.md, alerts.go
- Updating CHANGELOG.md
- Add missing fields
=> feat(alerts): Add missing fields

alerts.go
=> Add disable and notifiers fields on alert creation

CHANGELOG.md, logs.go
=> feat(logs): add timestamp to the logs URL

CHANGELOG.md, client.go, databases.go, scalingomock/api_mock.go
=> Add ability to add/remove database features

CHANGELOG.md, apps.go, data_access_consent.go
This is the bare minimum, waiting for the full API to be released
=> feature(data_access_consent) Add support for data_access_consent

CHANGELOG.md, events_structs.go
Add detached field for EventRun following this [PR](https://github.com/Scalingo/api/pull/2077)
=> feat: add detached field for EventRun

CHANGELOG.md, container.go
=> style(kill): Send signal renamed Kill

CHANGELOG.md, http/errors.go
=> feat(status code): handle too many requests exception

CHANGELOG.md, apps.go
Related to https://github.com/Scalingo/cli/issues/890
=> feat(apps): add support for hds_resource

operations.go
Applied a rename idea from @Soulou 
Adds to https://github.com/Scalingo/go-scalingo/issues/313
=> fix(one-off): renamed oneoffdata to startoneoffdata

events_boilerplate.go, events_specialize.go, events_structs.go
=> feat(events): add data to EventLinkScm, create EventUpdateLinkScm

CHANGELOG.md, scm_repo_link.go
Fixes https://github.com/Scalingo/go-scalingo/issues/331
=> feat(scm_repo_link): add ManualDeployResponse

CHANGELOG.md, README.md, version.go
=> Bump v6.5.0

CHANGELOG.md, README.md, version.go
=> Bump v6.6.0

events_boilerplate.go, events_specialize.go, events_structs.go
=> feat: review app event

CHANGELOG.md, databases.go, maintenance.go
=> feat(maintenance): add maintenance show

CHANGELOG.md, README.md, version.go
=> Bump v6.7.0

CHANGELOG.md, databases.go, maintenance.go
=> Change maintenance listing pagination meta to standard pagination meta

CHANGELOG.md, README.md, version.go
=> Bump v6.7.2

CHANGELOG.md, README.md, version.go
=> Bump v6.7.3

maintenance.go
=> fix(maintenance): remove maintenanceType because it cannot be used

CHANGELOG.md, README.md, version.go
=> Bump v6.7.5

CHANGELOG.md, README.md, version.go
=> Bump v6.7.7

CHANGELOG.md, collaborators.go, mocks_sig.json, scalingomock/api_mock.go, scalingomock/collaboratorsservice_mock.go
=> [STORY-1890] Add support for limited collaborators

.github/CODEOWNERS, .github/dependabot.yml
=> build: move Dependabot reviewers to CODEOWNERS

Dockerfile, go.mod, http/api_request.go
=> [STORY-2085] update to Go 1.24

events_structs.go, events_structs_test.go
When collaborator username is not available, fallback on email only message
=> [STORY-1429] Fix EventChangeCollaboratorRole when pending collaborator

CHANGELOG.md, events_boilerplate.go, events_specialize.go, events_structs.go
=> [STORY-2061] Add Event::NewProject event

CHANGELOG.md, events_boilerplate.go, events_specialize.go, events_structs.go
=> [STORY-2175] Add delete_project event

CHANGELOG.md, events_boilerplate.go, events_specialize.go, events_structs.go, events_structs_test.go
=> [STORY-2177] Create modify project event

CHANGELOG.md, events_app.go, events_boilerplate.go, events_specialize.go, events_structs.go, events_structs_test.go
=> [STORY-2176] Add update app project event

CHANGELOG.md, README.md, version.go
=> Bump v8.2.0

CHANGELOG.md, README.md, version.go
=> Bump v8.3.0

CHANGELOG.md, events_structs.go, events_structs_test.go
=> [Story-2487] feat(project-squared) Add data to delete project event

CHANGELOG.md, client.go, databases_preview.go
=> [STORY-2511] Add support for database next generation related actions

CHANGELOG.md, README.md, version.go
=> Bump v8.5.0
