Scalingo/go-scalingo

- events_types.go
I will update the CLI when this is merged
Related to Scalingo/cli#386
> Add missing spaces in alert description

- http/client.go
> Default SCALINGO_DB_URL should not include the /api path

- operations.go
Fixes #91
Operation URL is fetched from `AppsRestart()`/`AppsScale()` headers
So I think it's usefull not to oblige the client to parse the URL to put the right IDs
> Expand Operation API use types and new helper method

- notifier_types.go
- notifiers.go
> No need to know the name of the notifier type, just the platform ID when creating or updating a notifier

- integrations.go
> Added scm integrations types

- CHANGELOG.md
- scm_repo_link.go
> Remove SCMIntegrationUUID field on structs

- client.go
> Add StaticTokenGenerator for AuthAPI, to use a JWT Token instead of the basic token.

- CHANGELOG.md
- region_migrations.go
This change was made when we were adding the run endpoints https://github.com/Scalingo/storky/commit/7501cb13c2ff359846df83a44fb04e77411faee3
> [Migrations] Rename scheduled to created status

- CHANGELOG.md
- README.md
- events_structs.go
The event `restart` and `edit_variable` might be created by an addon. It currently lacks the `Who` method for these events.
Related to Scalingo/cli#530
> Fix Who created an event for restart and edit_variable

- CHANGELOG.md
- log_drains.go
- log_drains_test.go
Related to https://github.com/Scalingo/api/issues/1713
> Update GET /log_drains to return object with array instead of directly an array

- client.go
- http/api_request.go
- http/client.go
Currently changing the /v1 prefix for the API endpoint was impossible but was required for internal usages of the API, this PR allows this
> Make API version prefix more easily configurable by user

- CHANGELOG.md
- http/api_request.go
[GRR-94]
This pollutes the log, does not give more information for debug, and leaks the JWT token 👎🏻 
Example of log:
```text
fail to parse JSON of subresource response: fail to parse JSON of request &{GET https://api.scalingo.com/v1/apps/test? HTTP/1.1 1 1 map[Accept:[application/json] Authorization:[Bearer ...] Content-Type:[application/json] User-Agent:[Scalingo Go Client]] <nil> <nil> 0 [] false api.scalingo.com map[] map[] <nil> map[] <nil> <nil> <nil> 0xc0001f3200}, json: cannot unmarshal string into Go value of type scalingo.App
```
[GRR-94]: https://scalingo.atlassian.net/browse/GRR-94
> Remove headers from Request of http.parseJSON returned error

- CHANGELOG.md
- apps.go
Related to [GRR-42]
[GRR-42]: https://scalingo.atlassian.net/browse/GRR-42
> feature(app): Add `Limits` field to App

- CHANGELOG.md
- apps.go
- mocks_sig.json
- scalingomock/api_mock.go
- scalingomock/appsservice_mock.go
The PR #204 introduced an API change which would have require a new major release. But as stated in the Go module documentation (https://blog.golang.org/v2-go-modules):
> These kinds of changes require effort by downstream users to migrate their code to the new API, so they should not be made without careful consideration that the benefits outweigh the costs
In this situation, I don't think that the benefits outweigh the costs. Hence I'm reverting the API changes so that we don't break the API anymore.
Related to [OPSB-257]
[OPSB-257]: https://scalingo.atlassian.net/browse/OPSB-257
> fix: restore previous AppsPs and rename AppsPs to AppsContainersPs

- CHANGELOG.md
- auth_mock.go
- client_test.go
- go.mod
- go.sum
- http/api_token_generator.go
- http/api_token_generator_test.go
As specified in [github.com/dgrijalva/jwt-go](https://github.com/dgrijalva/jwt-go) README, the repository is no longer maintained and has been replaced with [github.com/golang-jwt/jwt](https://github.com/golang-jwt/jwt). The [migration guide](https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md) is rather simple, it should work as is.
> build(deps): replace deprecated github.com/dgrijalva/jwt-go with github.com/golang-jwt/jwt

- CHANGELOG.md
- tokens.go
The `ID` of the token struct was not correctly deserialized.
Alos the `LastUsedAt` field was missing, I added it.
> Update the token struct

- CHANGELOG.md
- deployments.go
- mocks_sig.json
- scalingomock/api_mock.go
- scalingomock/deploymentsservice_mock.go
Currently, the `DeploymentList` method does not support the pagination. I added a new parameter to it. If you don't want to break the API, we may add a new method with it.
> Add pagination on the DeploymentList method.

- CHANGELOG.md
- events_boilerplate.go
- events_structs.go
Fix https://github.com/Scalingo/cli/issues/682
> feat(events) Implement event for repeated crash

- CHANGELOG.md
- addons.go
> feat(addon-logs-archives): add AddonLogsArchives method

- CHANGELOG.md
- addons.go
- auth_mock.go
- http/api_request.go
- logs-archives.go
> refactor: replace use of the deprecated ioutil package

- CHANGELOG.md
- log_drains.go
- mocks_sig.json
- scalingomock/api_mock.go
- scalingomock/logdrainsservice_mock.go
- The `LogDrain` struct was used for both the return of the log drains list methods and to create a new log drain. As the return of the API only return the URL, I thought it would be simpler to only returns a struct that match that.
- the `LogDrainsAddonList` now returns the list of log drains to be consistent with other methods
> Update LogDrains API

- README.md
Fix how we import go-scalingo in the README to prevent the confusion reported in #247.
> docs(readme): fix go-scalingo import

- CHANGELOG.md
- events_boilerplate.go
- events_structs.go
[DOC-89]
[DOC-89]: https://scalingo.atlassian.net/browse/DOC-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(events): add two factor auth events

- addons_providers.go
All fields related to prices are deleted.
source: https://github.com/Scalingo/terraform-provider-scalingo/issues/51#issuecomment-1248009766
> fix(addon provider): delete price field from plan's structure

- CHANGELOG.md
- scm_repo_link.go
> fix(scm_repo_link): URL field added in the SCMRepoLink structure

- CHANGELOG.md
- container.go
> feat(send-signal): new function `ContainersSendSignal` to request the send-signal api's endpoint

- CHANGELOG.md
- deployments.go
`image_size` has recently been added (https://developers.scalingo.com/deployments)
Related to https://github.com/Scalingo/cli/issues/889
> feat(deployments): add support for Deployment image_size

- CHANGELOG.md
- README.md
- version.go
* feat(apps): add support for `hds_resource`
* feat(deployments): add support for Deployment `image_size`
* feat(events): Stack changed event
BREAKING CHANGE:
* Remove the `GithubLinkService` in favor of `SCMRepoLinkService`
> Bump v6.3.0

- CHANGELOG.md
- backups.go
This is an attempt at triggering the CI.
Replaces #310
> feat(backup): add `StartedAt` and `Method` fields

- CHANGELOG.md
- README.md
- version.go
> Bump v6.4.0

- stacks_test.go
- users.go
Nit pull request.
I see an opportunity to reduce a small nesting piece of code. It's not a big deal but i assume it can save some memory usage by removing `var user *User`.
Reference:
https://github.com/uber-go/guide/blob/master/style.md#reduce-nesting
> refactor(users): reduce nesting

- scm_repo_link.go
> feat: query data of a single pull request

- CHANGELOG.md
- tokens.go
This is only used in the CLI in our codebase:
https://github.com/Scalingo/cli/blob/9e342bdf9d3c04a80a14455c6a4786ed19142b74/config/auth.go#L260
I'll create a PR to update it there.
I kept the error declaration in the `http` package as it seems more relevant to have it in this package. It is a nicer Go error for a HTTP error returned by the API.
Fix #360
I don't think it is worth a changelog entry in the global Scalingo changelog
> refactor(tokens): deprecate `ErrOTPRequired` and `IsOTPRequired`

- CHANGELOG.md
- events_app.go
- events_structs_test.go
no need for changelog entry, open to suggestions on the sentence
thought about "containers are restarting" but time used isn't past
fixes #324
> fix(wording): ambiguous event name when restarting containers

- CHANGELOG.md
- alerts.go
- alerts_test.go
- apps_test.go
- billing/profile.go
- client.go
- client_test.go
- cron_tasks_test.go
- domains_test.go
- events_billing.go
- events_structs.go
- events_structs_test.go
- events_user.go
- go.mod
- go.sum
- http/api_request.go
- http/api_token_generator.go
- http/client.go
- http/errors.go
- log_drains_test.go
- notifier_types.go
- regions.go
- scm_repo_link.go
- signup.go
- stacks_test.go
- static_token.go
I also took the opportunity to fix all linter offenses.
Fix #326
> fix(events): app run event wording

- CHANGELOG.md
- databases.go
Related to https://github.com/Scalingo/cli/issues/1018
> feat(database): add user management routes

- CHANGELOG.md
- events_structs.go
Tested in the CLI PR https://github.com/Scalingo/cli/pull/1023
Bug introduced here: https://github.com/Scalingo/api/commit/f3cb678bdfc10084ead9d609f2dc4c977ec75c29#diff-f82734ec66b682822460f5f57892cb41ece508296c00270b648a4d2e442df75bR7
Related to https://github.com/Scalingo/cli/issues/1022
> fix(events): `link_scm` data types

- CHANGELOG.md
- http/errors.go
- http/errors_test.go
Fix https://github.com/Scalingo/cli/issues/1029
> fix(error): invalid return on `IsOtpError`

- CHANGELOG.md
- databases.go
- http/client.go
Related to https://github.com/Scalingo/cli/issues/1034
> feat(database): add database user password update route

- CHANGELOG.md
- apps.go
> feat: add private_network_ids field for the app model

- CHANGELOG.md
- databases.go
Added DatabaseUserPasswordReset method
> [STORY-642] new api endpoint to handle password reset

- CHANGELOG.md
- README.md
- version.go
> [STORY-642] Bump v7.0.1

- CHANGELOG.md
- run.go
> fix(one-off): remove async field from the run command

- go.mod
- go.sum
Replaces #407 where the CI fails for a reason I don't understand. It complains about the Go version:
```
Go versions do not match between go.mod and Dockerfile (1.24.3 != 1.24)
```
But 1.24.3 is never declared anywhere...
> chore(deps): bump the dependencies group across 1 directory with 2 updates

- CHANGELOG.md
- README.md
- collaborators.go
- mocks_sig.json
- scalingomock/api_mock.go
- scalingomock/collaboratorsservice_mock.go
This PR adds a new method to update a collaborator. Right now only the `is_limited` attribute is supported.
- Done [here](https://github.com/Scalingo/documentation/pull/3252)
> [STORY-2252] Add support for updating a collaborator

- CHANGELOG.md
- apps.go
- http/errors.go
- projects.go
This PR adds the support for all the `projects` endpoint from the [documentation](https://developers.scalingo.com/projects).
This will be QAed with the CLI, and will probably be merged in ~last~ first one all PRs are ready and reviewed.
EDIT: QA went fine with the two PRs using that change.
> [STORY-2323] Add "projects" management
